- name: Get state and config data from SR Linux
  hosts: all
  gather_facts: false
  tasks:
    - name: Get hostname, version and tls-profile
      nokia.srlinux.get:
        paths:
          - path: /system/name/host-name
          - path: /system/information/version
          - path: /system/json-rpc-server/network-instance[name=mgmt]/https/tls-profile
      register: get_result

    - ansible.builtin.debug:
        msg: "Host {{get_result.result[0]}} runs {{get_result.result[1]}} version and json-rpc server uses '{{get_result.result[2]}}' TLS profile"
