- name: Configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Various configuration tasks
      nokia.srlinux.config:
        replace:
          - path: /interface[name=mgmt0]/description
            value: "{{inventory_hostname}} management interface"
        update:
          - path: /system/information
            value:
              location: the Netherlands
              contact: Roman Dodin
          - path: /
            value: "{{lookup('ansible.builtin.template', '{{playbook_dir}}/iface-cfg.json.j2') }}"
      register: set_result

    - name: Verify configuration set
      nokia.srlinux.get:
        paths:
          - path: /interface[name=mgmt0]/description
          - path: /system/information
          - path: /interface[name=ethernet-1/1]/description
          - path: /interface[name=lo0]/description
      register: get_result

    - ansible.builtin.debug:
        msg:
          - "mgmt0 description is: {{get_result.result[0]}}"
          - "location is: {{get_result.result[1].location}}"
          - "contact is: {{get_result.result[1].contact}}"
          - "ethernet-1/1 description is: {{get_result.result[2]}}"
          - "loopback0 description is: {{get_result.result[3]}}"

    # - ansible.builtin.debug:
    #     msg: "{{get_result.json.result[2].}}"
