- name: Replace operation
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Replace partial config
      ansible.builtin.uri:
        url: http://{{inventory_hostname}}/jsonrpc
        url_username: admin
        url_password: NokiaSrl1!
        method: POST
        body:
          jsonrpc: "2.0"
          id: 1
          method: set
          params:
            commands:
              - action: replace
                path: /interface[name=ethernet-1/1]
                value:
                  name: ethernet-1/1
                  admin-state: disable
              - action: delete
                path: /network-instance[name=default]/interface[name=ethernet-1/1.0]
        body_format: json
      register: set_result

    - name: Stop if request contains error
      ansible.builtin.fail:
        msg: "Error: {{set_result.json.error.message}}"
      when: set_result.json.error is defined

    - name: Verify configuration set
      ansible.builtin.uri:
        url: http://{{inventory_hostname}}/jsonrpc
        url_username: admin
        url_password: NokiaSrl1!
        method: POST
        body:
          jsonrpc: "2.0"
          id: 2
          method: get
          params:
            datastore: running
            commands:
              - path: /interface[name=ethernet-1/1]
        body_format: json
      register: get_result

    - ansible.builtin.debug:
        var: get_result.json.result
