- name: Replace operation
  hosts: all
  gather_facts: false
  tasks:
    - name: Replace partial config
      nokia.srlinux.config:
        replace:
          - path: /interface[name=ethernet-1/1]
            value:
              name: ethernet-1/1
              admin-state: disable
        delete:
          - path: /network-instance[name=default]/interface[name=ethernet-1/1.0]
      register: set_result

    - name: Verify configuration set
      nokia.srlinux.get:
        paths:
          - path: /interface[name=ethernet-1/1]
            datastore: running
      register: get_result

    - ansible.builtin.debug:
        var: get_result.result
