- name: Operational commands
  hosts: all
  gather_facts: false
  vars:
    commands:
      - show version
      - show platform chassis
  tasks:
    - name: Fetch show commands output
      nokia.srlinux.cli:
        commands: "{{commands}}"
        output_format: text
      register: cli_result

    - name: Save fetched show outputs
      ansible.builtin.copy:
        content: "{{item}}"
        dest: '{{playbook_dir}}/{{inventory_hostname}}.{{ commands[idx] | replace(" ", "-") | regex_replace("[^A-Za-z0-9\-]", "") }}.txt'
      loop: "{{cli_result.result}}"
      loop_control:
        index_var: idx
