- name: Replace operation
  hosts: all
  gather_facts: false
  tasks:
    - name: Replace entire config
      nokia.srlinux.config:
        replace:
          - path: /
            value: "{{lookup('ansible.builtin.template', '{{playbook_dir}}/golden.cfg.json.j2') }}"
      register: set_result

    - name: Verify configuration set
      nokia.srlinux.get:
        paths:
          - path: /system/information/location
            datastore: state
      register: get_result

    - ansible.builtin.debug:
        msg: "Location from golden config: {{get_result.result[0]}}"
